In [1]:
import pandas as pd
housnig = pd.read_csv('./housing.csv')


def housingFilter(data, columns: str | list[str], filterColumsName: str, filtervalue: str | int):
    return data[columns][data[filterColumsName] == filtervalue]
  
# housnig.head(2)
# housnig.tail(10)
# housnig[2:7]
# housnig[:7]
# housnig[-5:]
# housnig.shape
# housnig.info()
# housnig.columns
# housnig['ocean_proximity'].unique()
# housnig['ocean_proximity'].value_counts()
# housnig['total_rooms'].value_counts()
# housingFilter = housnig[['households', 'median_income']
#         ][housnig['ocean_proximity'] == 'INLAND']
# housnig.describe()


housingFilter(housnig, ['households',
                        'median_income'], 'ocean_proximity', 'INLAND')

       households  median_income
954         208.0         5.1406
957        1115.0         6.4994
965         286.0         7.3330
967         577.0         6.5214
968         324.0         6.4524
...           ...            ...
20635       330.0         1.5603
20636       114.0         2.5568
20637       433.0         1.7000
20638       349.0         1.8672
20639       530.0         2.3886

[6551 rows x 2 columns]